PROMPTS = [
    "What would you do with an extra hour every day?",
    "Describe your perfect weekend.",
    "Tell me about the last thing that made you laugh.",
    "What's something you're looking forward to?",
    "If you could have dinner with anyone, who and why?",
    "What's a skill you'd like to master this year?",
    "Describe a place that feels like home to you.",
    "What's the best advice you've ever received?",
    "Tell a story about a time you overcame a fear.",
    "What habit has improved your life the most?",
    "If you could learn one thing instantly, what would it be?",
    "What's a small joy you look for every day?",
    "Describe someone who changed how you see the world.",
    "What's a book, film, or song that stuck with you?",
    "What would your ideal morning look like?",
    "Tell me about a mistake that taught you something valuable.",
    "What cause would you speak up for in front of a crowd?",
    "What's one thing you're grateful for right now?",
    "If you could revisit any day from your past, which would it be?",
    "Describe a tradition you want to keep or start.",
    "What's something you're proud of that others might not notice?",
    "How do you recharge when life gets loud?",
    "What question do you wish people asked you more often?",
    "Describe a goal you're working toward and why it matters.",
    "What's a lesson from childhood you still use today?",
]
